# Generated by Django 4.2.4 on 2023-09-03 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_data_de_nascimento_user_date_of_birth_and_more'),
        ('movies', '0002_rename_descricao_movie_description_and_more'),
        ('movie_comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('note', models.FloatField(help_text='Digite um valor de 0 à 10.')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.DeleteModel(
            name='WatchedMovies',
        ),
    ]
