# Generated by Django 4.2.4 on 2023-09-03 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_comments', '0002_moviecomments_delete_watchedmovies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviecomments',
            old_name='note',
            new_name='rate',
        ),
    ]
