# Generated by Django 4.2.4 on 2023-09-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_comments', '0003_rename_note_moviecomments_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecomments',
            name='rate',
            field=models.FloatField(help_text='Enter a number from 0 to 10.'),
        ),
    ]
