# Generated by Django 4.2.4 on 2023-09-04 19:44

import apps.movie_comments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_comments', '0004_alter_moviecomments_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecomments',
            name='rate',
            field=models.FloatField(help_text='Enter a number from 0 to 10.', max_length=4, validators=[apps.movie_comments.models.validaFloat]),
        ),
    ]
