# Generated by Django 4.2.4 on 2023-09-03 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='ano_de_lancamento',
            new_name='release_year',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='titulo',
            new_name='title',
        ),
    ]
